export const menus = [{
  displayName:"管理",
  icon:"el-icon-setting",
  role:["AbpIdentity","AbpTenantManagement"],
  visible:false,
  target:"group",
  children:[{
      displayName:"身份认证管理",
      role:["AbpIdentity"],
      visible:false,
      children:[
      {
        displayName:"角色",
        route:"/identity/roles",
        role:"AbpIdentity.Roles",
        visible:false,
      },{
        displayName:"用户",
        route:"/identity/users",
        role:"AbpIdentity.Users",
        visible:false
      }
    ]},
    {
      displayName:"租户管理",
      role:["AbpTenantManagement"],
      visible:false,
      children:[
      {
        displayName:"租户",
        route:"/tenant/tenants",
        role:"AbpTenantManagement.Tenants",
        visible:false
      }
    ]}
  ]
}]
